/*create schema if not exists test;

drop table if exists booking;
drop table if exists category;
drop table if exists room;
drop table if exists user;
drop table if exists option;
drop table if exists booking_option;

create table category
(
  id   bigint(19) auto_increment not null,
  name varchar(20),
  primary key (id)
);


create table room
(
  id          bigint(19) auto_increment not null,
  number      integer(10),
  price       decimal(19, 2),
  category_id bigint(19),
  primary key (id),
  foreign key (category_id) references category (id)
);


create table user
(
  id    bigint(19) auto_increment not null,
  name  varchar(200),
  phone varchar(20),
  primary key (id)
);


create table option
(
  id    bigint(19) auto_increment not null,
  name  varchar(200),
  price decimal(19, 2),
  primary key (id)
);


create table booking
(
  id         bigint(19) auto_increment not null,
  end_date   date(10),
  start_date date(10),
  room_id    bigint(19),
  user_id    bigint(19),
  primary key (id),
  foreign key (room_id) references room (id),
  foreign key (user_id) references user (id)
);


create table booking_option
(
  booking_id bigint(19),
  option_id  bigint(19),
  foreign key (option_id) references option (id),
  foreign key (booking_id) references booking (id)
)*/

drop table if exists booking;
drop table if exists booking_option;
drop table if exists category;
drop table if exists option;
drop table if exists room;
drop table if exists user;

create table category (
  id   bigint generated by default as identity,
  name varchar(255),
  primary key (id)
);

create table option (
  id    bigint generated by default as identity,
  name  varchar(255),
  price decimal(19, 2),
  primary key (id)
);

create table user (
  id    bigint generated by default as identity,
  name  varchar(255),
  phone varchar(255),
  primary key (id)
);

create table room (
  id          bigint generated by default as identity,
  number      integer,
  price       decimal(19, 2),
  category_id bigint,
  primary key (id),
  foreign key (category_id) references category(id),
);

create table booking (
  id         bigint generated by default as identity,
  end_date   date,
  start_date date,
  room_id    bigint,
  user_id    bigint,
  primary key (id),
    foreign key (room_id) references room (id),
  foreign key (user_id) references user (id)
);

create table booking_option (
  option_id  bigint not null,
  booking_id bigint not null,
  foreign key (option_id) references booking(id),
    foreign key (booking_id) references option(id)
);








/*
alter table booking
  add constraint FKq83pan5xy2a6rn0qsl9bckqai foreign key (room_id) references room;
alter table booking
  add constraint FKkgseyy7t56x7lkjgu3wah5s3t foreign key (user_id) references user;
alter table booking_option
  add constraint FK6y4s2xctjtrajwq2oenuh4lou foreign key (booking_id) references option;
alter table booking_option
  add constraint FK94j8tm7nfhmht0y84xaxjxhou foreign key (option_id) references booking;
alter table room
  add constraint FKllkgnps1iryk3347aokxwbxxm foreign key (category_id) references category;*/
