drop table if exists booking;
drop table if exists booking_option;
drop table if exists category;
drop table if exists option;
drop table if exists room;
drop table if exists user;

create table category (
  id   bigint generated by default as identity,
  name varchar(255),
  primary key (id)
);

create table option (
  id    bigint generated by default as identity,
  name  varchar(255),
  price decimal(19, 2),
  primary key (id)
);

create table user (
  id    bigint generated by default as identity,
  name  varchar(255),
  phone varchar(255),
  primary key (id)
);

create table room (
  id          bigint generated by default as identity,
  number      integer,
  price       decimal(19, 2),
  category_id bigint,
  primary key (id),
  foreign key (category_id) references category(id),
);

create table booking (
  id         bigint generated by default as identity,
  end_date   date,
  start_date date,
  room_id    bigint,
  user_id    bigint,
  primary key (id),
  foreign key (room_id) references room (id),
  foreign key (user_id) references user (id)
);

create table booking_option (
  option_id  bigint not null,
  booking_id bigint not null,
  foreign key (option_id) references booking(id),
  foreign key (booking_id) references option(id)
);

